# DigitalOcean App Platform Configuration
# Emergency Recovery Deployment for AXSUSDT Ultra-High Frequency Trading Bot
# Recovery Token: c45618c0-7e36-4600-b4c1-eb8918326179

name: quantum-trading-bot-emergency
region: nyc1

services:
- name: trading-bot
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/quantum_trading_bot
  build_command: pip install --no-cache-dir -r requirements.txt
  run_command: python -u main.py
  instance_count: 1
  instance_size_slug: basic-xxs
  environment_slug: python
  
  envs:
  # Core Configuration
  - key: ENVIRONMENT
    value: "production"
  - key: BINANCE_TESTNET
    value: "false"
  - key: DEBUG
    value: "false"
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PYTHONPATH
    value: "."
  - key: PORT
    value: "8080"
  - key: HEALTH_CHECK_PORT
    value: "8080"
  - key: TZ
    value: "UTC"
  
  # AXSUSDT Ultra-High Frequency Trading Configuration
  - key: RISK_PER_TRADE
    value: "0.15"
  - key: DEFAULT_LEVERAGE
    value: "8.5"
  - key: MAX_LEVERAGE
    value: "10"
  - key: MIN_LEVERAGE
    value: "8"
  - key: MAX_CONCURRENT_POSITIONS
    value: "1"
  - key: STOP_LOSS_PERCENT
    value: "0.012"
  - key: TAKE_PROFIT_RATIO
    value: "1.5"
  
  # High-Frequency Trading Optimization
  - key: SIGNAL_GENERATION_INTERVAL
    value: "30"
  - key: MIN_SIGNAL_INTERVAL
    value: "15"
  - key: ORDER_TIMEOUT
    value: "5"
  - key: TARGET_TRADES_PER_DAY
    value: "22"
  
  # CRITICAL: Set these in DigitalOcean App Platform Dashboard
  # - key: BINANCE_API_KEY
  #   value: "YOUR_ACTUAL_BINANCE_API_KEY"
  # - key: BINANCE_SECRET_KEY
  #   value: "YOUR_ACTUAL_BINANCE_SECRET_KEY"
  
  # Optional: Telegram Notifications
  # - key: TELEGRAM_BOT_TOKEN
  #   value: "YOUR_TELEGRAM_BOT_TOKEN"
  # - key: TELEGRAM_CHAT_ID
  #   value: "YOUR_TELEGRAM_CHAT_ID"
  
  http_port: 8080
  
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  
  routes:
  - path: /
    preserve_path_prefix: false

# Alert and monitoring configuration
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
- rule: CPU_UTILIZATION
  value: 80
- rule: MEM_UTILIZATION
  value: 85